import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import { getServerSession } from "next-auth";
import { simplcms, SiteProvider, AdminToolbar, Navigation } from "simplcms";
import { User } from "simplcms/types";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const platformConfiguration = simplcms.platform.getPlatformConfiguration();
  const cookieStore = await cookies();
  const darkModeCookie = cookieStore.get("darkMode");
  const darkMode = darkModeCookie?.value === "true";
  let user: User | null = null;
  if (platformConfiguration.database && platformConfiguration.oauth) {
    const session = await getServerSession();
    if (session?.user?.email) {
      user = await simplcms.users.getUserByEmail(session.user.email);
    }
  }

  return (
    <html lang="en" className={darkMode ? "dark" : ""}>
      <body className="h-screen w-screen overflow-hidden">
        <SiteProvider initialSettings={{ darkMode }}>
          <div className="z-50 fixed w-screen top-0">
            <AdminToolbar user={user} />
            <Navigation />
          </div>
          {children}
        </SiteProvider>
      </body>
    </html>
  );
}
