import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";

import "./globals.css";
import { getServerSession } from "next-auth";
import { getUserByEmail } from "@/packages/core/src/user";
import { UserType } from "@/types/types";
import AdminToolbar from "./adminToolbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user: UserType | null = null;
  const session = await getServerSession();
  if (session && session.user.email)
    user = await getUserByEmail(session.user.email);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {user && session && <AdminToolbar />}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
