import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  // But you can create a sidebar manually

  gettingStarted: [{ type: "autogenerated", dirName: "getting-started" }],
  migrationGuide: [{ type: "autogenerated", dirName: "migration-guide" }],
  configuration: [{ type: "autogenerated", dirName: "configuration" }],
  markdownFeatures: [{ type: "autogenerated", dirName: "markdown-features" }],
  deployment: [{ type: "autogenerated", dirName: "deployment" }],
};

export default sidebars;
